window.ZX_DATA = {
  updatedAt: "2026-07-27 15:20（北京时间）",
  sources: [
    {
      name: "新浪娱乐",
      url: "https://data.ent.sina.com.cn/",
      note: "当天娱乐滚动、明星采访与活动信息",
    },
    {
      name: "微博奇遇记",
      url: "https://www.sina.cn/news/detail/5323459848570891.html",
      note: "8月8日-9日广州海心沙活动预售与阵容信息",
    },
    {
      name: "豆瓣 2026 国产剧片单",
      url: "https://m.douban.com/doulist/163128925/",
      note: "国产剧播出时间与条目信息",
    },
    {
      name: "哔哩哔哩综艺",
      url: "https://www.bilibili.com/variety/",
      note: "综艺视频与节目条目",
    },
    {
      name: "1905 电影网",
      url: "https://www.1905.com/mdb/film/2255197/",
      note: "电影预告与影片资料",
    },
    {
      name: "上映状态报道",
      url: "https://www.rfa.org/mandarin/zhengzhi/2026/07/22/china-taiwan-moive-unification-penghu-propaganda/",
      note: "《澎湖海战》上映状态追踪",
    },
  ],
  spotlights: [
    {
      tag: "活动",
      title: "微博奇遇记预售开启，8月8日-9日广州海心沙亚运公园举行",
      summary: "全明星船长阵容集结，活动地点为广州海心沙亚运公园。",
      category: "活动 明星 票务 热榜",
      date: "08-08",
      source: "新浪",
      url: "https://www.sina.cn/news/detail/5323459848570891.html",
      image: "assets/weibo-qiyuji-2.jpg",
      alt: "微博奇遇记明星船长集结活动宣传海报",
    },
    {
      tag: "电影",
      title: "2026 微博电影之夜荣誉揭晓，张艺谋、姜文等电影人亮相",
      summary: "年度电影盛事回顾，适合作为电影红毯与荣誉榜专题入口。",
      category: "电影 红毯 榜单 资讯",
      date: "06-14",
      source: "新浪娱乐",
      url: "https://ent.sina.com.cn/",
      image:
        "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1400&q=80",
      alt: "电影院座位与银幕",
    },
    {
      tag: "剧集",
      title: "暑期国产剧更新：《兵自风中来》《这一秒过火》等进入讨论区",
      summary: "豆瓣 2026 国产剧片单显示多部 7 月国产剧正在更新或上线。",
      category: "影视 剧集 热榜",
      date: "07-27",
      source: "豆瓣",
      url: "https://m.douban.com/doulist/163128925/",
      image:
        "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1400&q=80",
      alt: "影视片场灯光",
    },
  ],
  feeds: [
    {
      title: "微博奇遇记预售开启：8月8日-9日相约广州海心沙",
      summary: "明星船长阵容集结，官方购票与舒适座区信息已经放出。",
      category: "活动 明星 票务 热榜",
      channel: "活动日历",
      date: "08-08",
      metric: "预售开启",
      source: "新浪",
      url: "https://www.sina.cn/news/detail/5323459848570891.html",
      image: "assets/weibo-qiyuji-1.jpg",
      alt: "微博奇遇记全票种预售开启宣传海报",
    },
    {
      title: "2026 微博电影之夜荣誉单：电影人、演员与年度作品集中亮相",
      summary: "张艺谋获时代影响力导演，刘昊然、李庚希获年度品质演员等荣誉。",
      category: "电影 红毯 榜单 热榜",
      channel: "电影红毯",
      date: "06-14",
      metric: "荣誉汇总",
      source: "新浪娱乐",
      url: "https://ent.sina.com.cn/",
      image:
        "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=900&q=80",
      alt: "电影放映机与影院",
    },
    {
      title: "袁一琦首谈出道十年心路，新浪娱乐《转公开可见》正片上线",
      summary: "采访涉及出道十年、暂停工作原因和个人发展阶段。",
      category: "明星 采访 资讯",
      channel: "明星专访",
      date: "07-27",
      metric: "正片上线",
      source: "新浪娱乐",
      url: "https://k.sina.com.cn/article_6579479488_1882ae3c004001mo46.html?from=ent",
      image:
        "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=900&q=80",
      alt: "采访现场灯光",
    },
    {
      title: "《澎湖海战》原定 7月25日上映，最新状态需持续追踪",
      summary: "此前公开报道显示影片曾定档 7月25日；随后又有上映前传撤档、预售停摆的报道。",
      category: "电影 影视 资讯 热榜",
      channel: "电影定档",
      date: "状态追踪",
      metric: "原定07-25",
      source: "公开报道",
      url: "https://www.rfa.org/mandarin/zhengzhi/2026/07/22/china-taiwan-moive-unification-penghu-propaganda/",
      image:
        "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80",
      alt: "电影拍摄现场",
    },
    {
      title: "《兵自风中来》7月23日开播，欧豪、蓝盈莹主演军旅剧进入追剧榜",
      summary: "豆瓣国产剧片单与新浪电视剧热点均收录该剧播出信息。",
      category: "影视 剧集 资讯",
      channel: "国产剧",
      date: "07-23",
      metric: "正在播出",
      source: "豆瓣",
      url: "https://m.douban.com/doulist/163128925/",
      image:
        "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=900&q=80",
      alt: "电影银幕与观众",
    },
    {
      title: "《这一秒过火》张凌赫、王楚然剧集热度持续，7月档讨论升温",
      summary: "豆瓣片单显示该剧 7 月上线，相关话题在剧集社区持续发酵。",
      category: "影视 剧集 热榜",
      channel: "剧集热议",
      date: "07-19",
      metric: "话题升温",
      source: "豆瓣",
      url: "https://m.douban.com/doulist/163128925/",
      image:
        "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?auto=format&fit=crop&w=900&q=80",
      alt: "影院红色座椅",
    },
    {
      title: "《我们的歌》第六季在 B 站综艺区可追，跨代际音乐舞台适合补档",
      summary: "B 站条目介绍节目以跨地域、跨代际、跨风格歌手配对演唱为核心。",
      category: "综艺 音乐 舞台",
      channel: "综艺补档",
      date: "持续更新",
      metric: "音乐综艺",
      source: "哔哩哔哩",
      url: "https://www.bilibili.com/bangumi/media/md22381155",
      image:
        "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80",
      alt: "音乐现场的麦克风和灯光",
    },
    {
      title: "严浩翔 AI 翻唱相关争议引关注，艺人声音权益话题继续发酵",
      summary: "新浪娱乐滚动条目收录了相关公司态度与讨论入口。",
      category: "音乐 明星 资讯 热榜",
      channel: "音乐舆情",
      date: "07-27",
      metric: "声音权益",
      source: "新浪娱乐",
      url: "https://data.ent.sina.com.cn/",
      image:
        "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
      alt: "录音棚麦克风",
    },
    {
      title: "《功夫女足》路演城市讨论：下一站会去哪里成为影迷关注点",
      summary: "新浪娱乐当天滚动内容收录路演城市相关话题。",
      category: "电影 活动 路演",
      channel: "路演追踪",
      date: "07-27",
      metric: "城市征集",
      source: "新浪娱乐",
      url: "https://data.ent.sina.com.cn/",
      image:
        "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80",
      alt: "体育场灯光",
    },
    {
      title: "鹿晗演唱会票务折扣话题登上娱乐讨论区",
      summary: "新浪娱乐滚动信息中出现演唱会门票价格相关讨论。",
      category: "音乐 舞台 票务 热榜",
      channel: "演唱会",
      date: "07-27",
      metric: "票务热议",
      source: "新浪娱乐",
      url: "https://data.ent.sina.com.cn/",
      image:
        "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=900&q=80",
      alt: "演唱会观众举手互动",
    },
  ],
  schedules: [
    [
      {
        time: "07-25",
        title: "《澎湖海战》上映状态追踪",
        detail: "曾官宣定档 7月25日，随后出现撤档与预售停摆报道。",
        url: "https://www.rfa.org/mandarin/zhengzhi/2026/07/22/china-taiwan-moive-unification-penghu-propaganda/",
      },
      {
        time: "07-27",
        title: "新浪娱乐《转公开可见》袁一琦专访",
        detail: "正片 11:00 上线，聚焦出道十年与暂停工作原因。",
        url: "https://k.sina.com.cn/article_6579479488_1882ae3c004001mo46.html?from=ent",
      },
      {
        time: "08-08",
        title: "微博奇遇记 · 广州海心沙",
        detail: "8月8日-9日举办，预售与明星阵容已公开。",
        url: "https://www.sina.cn/news/detail/5323459848570891.html",
      },
      {
        time: "近期",
        title: "暑期国产剧追更",
        detail: "《兵自风中来》《这一秒过火》等 7 月剧集进入片单。",
        url: "https://m.douban.com/doulist/163128925/",
      },
    ],
    [
      {
        time: "07-27",
        title: "明星舆情观察",
        detail: "AI 翻唱、演唱会票务、粉丝应援等话题进入新浪娱乐滚动。",
        url: "https://data.ent.sina.com.cn/",
      },
      {
        time: "持续",
        title: "B 站音乐综艺补档",
        detail: "《我们的歌》第六季等综艺条目可追。",
        url: "https://www.bilibili.com/bangumi/media/md22381155",
      },
      {
        time: "07月",
        title: "国产剧暑期档",
        detail: "豆瓣 2026 国产剧片单持续更新播出条目。",
        url: "https://m.douban.com/doulist/163128925/",
      },
      {
        time: "08月",
        title: "明星活动预告",
        detail: "微博奇遇记成为 8 月初重点线下活动入口。",
        url: "https://www.sina.cn/news/detail/5323459848570891.html",
      },
    ],
  ],
  ranks: [
    {
      title: "微博奇遇记预售与阵容",
      heat: "活动 99",
      url: "https://www.sina.cn/news/detail/5323459848570891.html",
    },
    {
      title: "《澎湖海战》上映状态追踪",
      heat: "电影 94",
      url: "https://www.rfa.org/mandarin/zhengzhi/2026/07/22/china-taiwan-moive-unification-penghu-propaganda/",
    },
    {
      title: "袁一琦出道十年专访",
      heat: "明星 91",
      url: "https://k.sina.com.cn/article_6579479488_1882ae3c004001mo46.html?from=ent",
    },
    {
      title: "《这一秒过火》剧集讨论",
      heat: "剧集 87",
      url: "https://m.douban.com/doulist/163128925/",
    },
    {
      title: "严浩翔 AI 翻唱争议",
      heat: "音乐 82",
      url: "https://data.ent.sina.com.cn/",
    },
  ],
};
